name: predict_cognitive_function
channels:
    - conda-forge
dependencies:
    - python==3.6.1
    - pandas==0.24.2
    - nilearn==0.5.2
    - numpy==1.16.4
    - sklearn==0.21.2
    - nibabel==2.5.1